version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: university_DB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: university_user
      MYSQL_PASSWORD: university_password
      MYSQL_DATABASE: university_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
